name: TraitorsAndMiners
version: 0.0.1
description: Looks like you're trying to write a description, would you like help?
main: mc.Mitchellbrine.traitorsAndMiners.TraitorsAndMiners
depend: [TitleManager]
commands:
   startTAM:
      description: Starts the game!
      usage: /startTAM
      permission: bukkit.command.op
      permission-message: You don't have permission to perform this command, soory!
   supply:
      description: Supplies the players!
      usage: /supply
      permission: bukkit.command.op
      permission-message: You don't have permission to perform this command, soory!
   vote:
      description: Votes on next map!
      usage: /vote [map number]
      permission: bukkit.command.help
      permission-message: You don't have permission to perform this command, soory!